import type { Cast } from "@/types";
import {
  currentUser,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
  user10,
  user11,
  user12,
  user13,
  user14,
  user15,
} from "./users";

// Bangalore Casts
export const bangaloreCasts: Cast[] = [
  {
    id: "cast-blr-1",
    user: currentUser,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop",
    likes: 42,
    caption: "Found this amazing rooftop cafe in Koramangala. The sunset views are incredible! Anyone been here before?",
    comments: [
      { id: "c1", user: user1, text: "Where is this? Need to visit!" },
      { id: "c2", user: user2, text: "Love the vibes! Was there last weekend." },
    ],
    timestamp: "2 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 3,
    totalTips: 75,
    cityId: "bangalore",
    tribeId: "tribe-blr-food",
  },
  {
    id: "cast-blr-2",
    user: user1,
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=600&fit=crop",
    likes: 89,
    caption: "Morning cycling group ride through Cubbon Park. 15km done before 7am! Join us every Saturday.",
    comments: [
      { id: "c3", user: currentUser, text: "Count me in next week!" },
      { id: "c4", user: user3, text: "Best way to start the weekend." },
    ],
    timestamp: "5 hours ago",
    isLiked: true,
    isSaved: true,
    tipCount: 7,
    totalTips: 150,
    cityId: "bangalore",
    tribeId: "tribe-blr-cycling",
  },
  {
    id: "cast-blr-3",
    user: user2,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop",
    likes: 156,
    caption: "My terrace garden is finally blooming! Six months of patience paying off. Tomatoes, herbs, and flowers.",
    comments: [
      { id: "c5", user: user15, text: "Goals! Can you share your composting tips?" },
      { id: "c6", user: user1, text: "This is beautiful! Well done." },
    ],
    timestamp: "8 hours ago",
    isLiked: false,
    isSaved: true,
    tipCount: 12,
    totalTips: 300,
    cityId: "bangalore",
  },
  {
    id: "cast-blr-4",
    user: user3,
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    likes: 34,
    caption: "Hackathon at Whitefield co-working space this weekend. Building a neighborhood safety app. Who's in?",
    comments: [
      { id: "c7", user: currentUser, text: "Sounds awesome! I'll bring the pizza." },
    ],
    timestamp: "12 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 2,
    totalTips: 50,
    cityId: "bangalore",
    tribeId: "tribe-blr-tech",
  },
  {
    id: "cast-blr-5",
    user: user15,
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop",
    likes: 201,
    caption: "Free yoga session at Lalbagh Botanical Garden tomorrow at 6am. All levels welcome. Bring your own mat!",
    comments: [
      { id: "c8", user: user2, text: "I'll be there!" },
      { id: "c9", user: user1, text: "Can I bring my friend who's visiting?" },
      { id: "c10", user: user15, text: "Of course! Everyone is welcome." },
    ],
    timestamp: "1 day ago",
    isLiked: true,
    isSaved: false,
    tipCount: 15,
    totalTips: 450,
    cityId: "bangalore",
    tribeId: "tribe-blr-fitness",
  },
  {
    id: "cast-blr-6",
    user: user1,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop",
    likes: 67,
    caption: "Best filter coffee in Indiranagar! This place has been around for 30 years. A true local gem.",
    comments: [
      { id: "c11", user: user3, text: "Their masala dosa is legendary too!" },
    ],
    timestamp: "1 day ago",
    isLiked: false,
    isSaved: false,
    tipCount: 5,
    totalTips: 125,
    cityId: "bangalore",
    tribeId: "tribe-blr-food",
  },
];

// Mumbai Casts
export const mumbaiCasts: Cast[] = [
  {
    id: "cast-mum-1",
    user: user4,
    imageUrl: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&h=600&fit=crop",
    likes: 234,
    caption: "Marine Drive at golden hour. No filter needed. This city never stops surprising me.",
    comments: [
      { id: "c12", user: user5, text: "The queen's necklace never gets old!" },
      { id: "c13", user: user4, text: "Best view in Mumbai, hands down." },
    ],
    timestamp: "1 hour ago",
    isLiked: true,
    isSaved: true,
    tipCount: 18,
    totalTips: 500,
    cityId: "mumbai",
  },
  {
    id: "cast-mum-2",
    user: user5,
    imageUrl: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=800&h=600&fit=crop",
    likes: 78,
    caption: "Street food tour in Andheri West. Vada pav, pani puri, and more. Mumbai's food scene is unmatched!",
    comments: [
      { id: "c14", user: user4, text: "You missed the best sev puri stall around the corner!" },
    ],
    timestamp: "3 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 4,
    totalTips: 100,
    cityId: "mumbai",
    tribeId: "tribe-mum-food",
  },
  {
    id: "cast-mum-3",
    user: user4,
    imageUrl: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=800&h=600&fit=crop",
    likes: 145,
    caption: "Caught the local train at peak hours. An experience everyone should try at least once!",
    comments: [
      { id: "c15", user: user5, text: "The real Mumbai experience right there." },
    ],
    timestamp: "6 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 8,
    totalTips: 200,
    cityId: "mumbai",
  },
  {
    id: "cast-mum-4",
    user: user5,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    likes: 56,
    caption: "Monsoon trek to Karnala Fort. The waterfall trails are magical right now. Weekend group forming!",
    comments: [
      { id: "c16", user: user4, text: "Count me in! Need a good trek." },
    ],
    timestamp: "10 hours ago",
    isLiked: true,
    isSaved: false,
    tipCount: 3,
    totalTips: 75,
    cityId: "mumbai",
    tribeId: "tribe-mum-fitness",
  },
  {
    id: "cast-mum-5",
    user: user4,
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=600&fit=crop",
    likes: 312,
    caption: "Bollywood night at Bandra amphitheatre! Live music, dancing, and great energy. Mumbai knows how to party.",
    comments: [
      { id: "c17", user: user5, text: "This was EPIC! Best night out in months." },
    ],
    timestamp: "1 day ago",
    isLiked: true,
    isSaved: true,
    tipCount: 22,
    totalTips: 600,
    cityId: "mumbai",
    tribeId: "tribe-mum-music",
  },
  {
    id: "cast-mum-6",
    user: user5,
    imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    likes: 45,
    caption: "Photography walk through Dharavi. Incredible stories, incredible people. Mumbai's heart beats here.",
    comments: [
      { id: "c18", user: user4, text: "Beautiful perspective. Would love to join next time." },
    ],
    timestamp: "2 days ago",
    isLiked: false,
    isSaved: true,
    tipCount: 6,
    totalTips: 150,
    cityId: "mumbai",
  },
];

// Delhi Casts
export const delhiCasts: Cast[] = [
  {
    id: "cast-del-1",
    user: user6,
    imageUrl: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=600&fit=crop",
    likes: 189,
    caption: "Heritage walk through Old Delhi. The architecture of Jama Masjid never ceases to amaze.",
    comments: [
      { id: "c19", user: user7, text: "Can I join the next one?" },
      { id: "c20", user: user6, text: "Absolutely! Next walk is this Saturday at 8am." },
    ],
    timestamp: "3 hours ago",
    isLiked: true,
    isSaved: true,
    tipCount: 14,
    totalTips: 350,
    cityId: "delhi",
  },
  {
    id: "cast-del-2",
    user: user7,
    imageUrl: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=800&h=600&fit=crop",
    likes: 92,
    caption: "Chandni Chowk food crawl. Paranthe wali gali is a must-visit for every foodie in Delhi!",
    comments: [
      { id: "c21", user: user6, text: "The aloo parantha there is legendary." },
    ],
    timestamp: "5 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 5,
    totalTips: 125,
    cityId: "delhi",
    tribeId: "tribe-del-food",
  },
  {
    id: "cast-del-3",
    user: user6,
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=600&fit=crop",
    likes: 267,
    caption: "Sunset at India Gate. Some views are timeless. Shared this moment with 200 fellow Delhiites.",
    comments: [
      { id: "c22", user: user7, text: "Magical shot! What camera did you use?" },
    ],
    timestamp: "8 hours ago",
    isLiked: true,
    isSaved: false,
    tipCount: 20,
    totalTips: 500,
    cityId: "delhi",
  },
  {
    id: "cast-del-4",
    user: user7,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
    likes: 43,
    caption: "Tree plantation drive in Saket. We planted 50 saplings today. Small steps, big impact.",
    comments: [
      { id: "c23", user: user6, text: "Proud of this community! Let's do more." },
    ],
    timestamp: "1 day ago",
    isLiked: false,
    isSaved: false,
    tipCount: 8,
    totalTips: 200,
    cityId: "delhi",
  },
  {
    id: "cast-del-5",
    user: user6,
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=600&fit=crop",
    likes: 178,
    caption: "Sufi night at Nizamuddin Dargah. The qawwali was soul-stirring. Delhi's cultural heritage is alive and well.",
    comments: [
      { id: "c24", user: user7, text: "One of the most powerful experiences in Delhi." },
    ],
    timestamp: "1 day ago",
    isLiked: true,
    isSaved: true,
    tipCount: 11,
    totalTips: 275,
    cityId: "delhi",
    tribeId: "tribe-del-arts",
  },
  {
    id: "cast-del-6",
    user: user7,
    imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&h=600&fit=crop",
    likes: 31,
    caption: "Weekend market at Dilli Haat. Picked up some amazing handicrafts from artisans across India.",
    comments: [
      { id: "c25", user: user6, text: "Dilli Haat is a treasure trove!" },
    ],
    timestamp: "2 days ago",
    isLiked: false,
    isSaved: false,
    tipCount: 2,
    totalTips: 50,
    cityId: "delhi",
  },
];

// San Francisco Casts
export const sanFranciscoCasts: Cast[] = [
  {
    id: "cast-sf-1",
    user: user8,
    imageUrl: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=800&h=600&fit=crop",
    likes: 198,
    caption: "Foggy morning run across Golden Gate Bridge. Nothing beats this view even at 6am!",
    comments: [
      { id: "c26", user: user9, text: "Karl the Fog strikes again! Great shot." },
    ],
    timestamp: "2 hours ago",
    isLiked: true,
    isSaved: true,
    tipCount: 16,
    totalTips: 400,
    cityId: "san-francisco",
    tribeId: "tribe-sf-fitness",
  },
  {
    id: "cast-sf-2",
    user: user9,
    imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=600&fit=crop",
    likes: 67,
    caption: "Demo day at our SoMa co-working space! 12 startups pitched today. The energy was electric.",
    comments: [
      { id: "c27", user: user8, text: "Congrats to all the teams! Innovation at its finest." },
    ],
    timestamp: "4 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 5,
    totalTips: 125,
    cityId: "san-francisco",
    tribeId: "tribe-sf-tech",
  },
  {
    id: "cast-sf-3",
    user: user8,
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop",
    likes: 124,
    caption: "Farm-to-table dinner at a Mission District pop-up. Supporting local farmers and chefs!",
    comments: [
      { id: "c28", user: user9, text: "How do I get on the invite list next time?" },
    ],
    timestamp: "7 hours ago",
    isLiked: false,
    isSaved: true,
    tipCount: 9,
    totalTips: 225,
    cityId: "san-francisco",
    tribeId: "tribe-sf-food",
  },
  {
    id: "cast-sf-4",
    user: user9,
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&h=600&fit=crop",
    likes: 89,
    caption: "Painted Ladies looking gorgeous today. Took a walking tour of Victorian architecture in Alamo Square.",
    comments: [
      { id: "c29", user: user8, text: "Classic SF! Never gets old." },
    ],
    timestamp: "12 hours ago",
    isLiked: true,
    isSaved: false,
    tipCount: 4,
    totalTips: 100,
    cityId: "san-francisco",
  },
  {
    id: "cast-sf-5",
    user: user8,
    imageUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop",
    likes: 156,
    caption: "Beach cleanup at Ocean Beach. 30 volunteers, 200 pounds of trash collected. Community power!",
    comments: [
      { id: "c30", user: user9, text: "This is what community looks like. Proud to be part of it." },
    ],
    timestamp: "1 day ago",
    isLiked: true,
    isSaved: false,
    tipCount: 20,
    totalTips: 500,
    cityId: "san-francisco",
  },
  {
    id: "cast-sf-6",
    user: user9,
    imageUrl: "https://images.unsplash.com/photo-1510137600163-2729bc6959e4?w=800&h=600&fit=crop",
    likes: 45,
    caption: "Exploring the murals in Balmy Alley. Street art that tells powerful stories of the Mission.",
    comments: [
      { id: "c31", user: user8, text: "The new mural on 24th is incredible too!" },
    ],
    timestamp: "2 days ago",
    isLiked: false,
    isSaved: false,
    tipCount: 3,
    totalTips: 75,
    cityId: "san-francisco",
    tribeId: "tribe-sf-arts",
  },
];

// London Casts
export const londonCasts: Cast[] = [
  {
    id: "cast-ldn-1",
    user: user10,
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop",
    likes: 345,
    caption: "Tower Bridge at dusk. 20 years in London and this view still takes my breath away.",
    comments: [
      { id: "c32", user: user11, text: "London is always a good idea!" },
    ],
    timestamp: "1 hour ago",
    isLiked: true,
    isSaved: true,
    tipCount: 28,
    totalTips: 700,
    cityId: "london",
  },
  {
    id: "cast-ldn-2",
    user: user11,
    imageUrl: "https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=800&h=600&fit=crop",
    likes: 78,
    caption: "Camden Market on a Sunday morning. Found the most amazing vintage leather jacket for a tenner!",
    comments: [
      { id: "c33", user: user10, text: "Bargain hunter! Show us the jacket." },
    ],
    timestamp: "4 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 3,
    totalTips: 75,
    cityId: "london",
  },
  {
    id: "cast-ldn-3",
    user: user10,
    imageUrl: "https://images.unsplash.com/photo-1576073719676-aa95576db207?w=800&h=600&fit=crop",
    likes: 212,
    caption: "Community pub quiz night in Shoreditch! Our team won for the third time. The trophy stays with us!",
    comments: [
      { id: "c34", user: user11, text: "Champions! Rematch next Thursday?" },
    ],
    timestamp: "6 hours ago",
    isLiked: true,
    isSaved: false,
    tipCount: 15,
    totalTips: 375,
    cityId: "london",
  },
  {
    id: "cast-ldn-4",
    user: user11,
    imageUrl: "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&h=600&fit=crop",
    likes: 95,
    caption: "Art exhibition at the Tate Modern. Contemporary pieces that challenge everything you think about space.",
    comments: [
      { id: "c35", user: user10, text: "The installation on the third floor is mind-blowing." },
    ],
    timestamp: "10 hours ago",
    isLiked: false,
    isSaved: true,
    tipCount: 6,
    totalTips: 150,
    cityId: "london",
    tribeId: "tribe-ldn-arts",
  },
  {
    id: "cast-ldn-5",
    user: user10,
    imageUrl: "https://images.unsplash.com/photo-1574180045827-681f8a1a9622?w=800&h=600&fit=crop",
    likes: 167,
    caption: "Borough Market food tour. Tried artisan cheese, fresh oysters, and the best sourdough in London.",
    comments: [
      { id: "c36", user: user11, text: "The cheese stall near the entrance is my favorite!" },
    ],
    timestamp: "1 day ago",
    isLiked: true,
    isSaved: false,
    tipCount: 10,
    totalTips: 250,
    cityId: "london",
    tribeId: "tribe-ldn-food",
  },
  {
    id: "cast-ldn-6",
    user: user11,
    imageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=800&h=600&fit=crop",
    likes: 54,
    caption: "Cycling along Regent's Canal. Peaceful, green, and perfect for a Sunday afternoon escape.",
    comments: [
      { id: "c37", user: user10, text: "One of London's best-kept secrets!" },
    ],
    timestamp: "2 days ago",
    isLiked: false,
    isSaved: false,
    tipCount: 4,
    totalTips: 100,
    cityId: "london",
    tribeId: "tribe-ldn-cycling",
  },
];

// New York Casts
export const newYorkCasts: Cast[] = [
  {
    id: "cast-nyc-1",
    user: user12,
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&h=600&fit=crop",
    likes: 278,
    caption: "Brooklyn Bridge at sunrise. Woke up at 4am for this shot. Worth every second of lost sleep!",
    comments: [
      { id: "c38", user: user13, text: "Stunning! This is why I love New York." },
      { id: "c39", user: user14, text: "I can see my apartment from here!" },
    ],
    timestamp: "2 hours ago",
    isLiked: true,
    isSaved: true,
    tipCount: 24,
    totalTips: 600,
    cityId: "new-york",
  },
  {
    id: "cast-nyc-2",
    user: user13,
    imageUrl: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?w=800&h=600&fit=crop",
    likes: 134,
    caption: "Salsa night in East Village! Teaching free classes every Friday. Come dance with us!",
    comments: [
      { id: "c40", user: user12, text: "Maria's classes are the best! Highly recommend." },
    ],
    timestamp: "4 hours ago",
    isLiked: true,
    isSaved: false,
    tipCount: 10,
    totalTips: 250,
    cityId: "new-york",
    tribeId: "tribe-nyc-arts",
  },
  {
    id: "cast-nyc-3",
    user: user12,
    imageUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&h=600&fit=crop",
    likes: 189,
    caption: "Community garden harvest in Williamsburg! Fresh tomatoes, basil, and peppers. Farm-to-table in the city.",
    comments: [
      { id: "c41", user: user13, text: "Can I get some basil for my kitchen?" },
      { id: "c42", user: user14, text: "This is so cool! How do I get a plot?" },
    ],
    timestamp: "7 hours ago",
    isLiked: false,
    isSaved: true,
    tipCount: 14,
    totalTips: 350,
    cityId: "new-york",
  },
  {
    id: "cast-nyc-4",
    user: user14,
    imageUrl: "https://images.unsplash.com/photo-1474224017946-8f6217e7d90a?w=800&h=600&fit=crop",
    likes: 23,
    caption: "First time running in Central Park! Training for my first 10K. Any running groups in the Upper West Side?",
    comments: [
      { id: "c43", user: user12, text: "Welcome! Check out the West Side Runners tribe." },
    ],
    timestamp: "12 hours ago",
    isLiked: false,
    isSaved: false,
    tipCount: 1,
    totalTips: 25,
    cityId: "new-york",
    tribeId: "tribe-nyc-fitness",
  },
  {
    id: "cast-nyc-5",
    user: user13,
    imageUrl: "https://images.unsplash.com/photo-1485182708500-e8f1f318ba72?w=800&h=600&fit=crop",
    likes: 245,
    caption: "Street performers in Washington Square Park. NYC's free entertainment is the best in the world.",
    comments: [
      { id: "c44", user: user12, text: "The jazz trio there on weekends is incredible." },
    ],
    timestamp: "1 day ago",
    isLiked: true,
    isSaved: false,
    tipCount: 18,
    totalTips: 450,
    cityId: "new-york",
    tribeId: "tribe-nyc-music",
  },
  {
    id: "cast-nyc-6",
    user: user12,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop",
    likes: 156,
    caption: "Pop-up dinner at my restaurant tonight! Korean-Mexican fusion. 30 seats, first come first served.",
    comments: [
      { id: "c45", user: user13, text: "Saved a seat! Your kimchi tacos are legendary." },
      { id: "c46", user: user14, text: "On my way!" },
    ],
    timestamp: "1 day ago",
    isLiked: false,
    isSaved: true,
    tipCount: 12,
    totalTips: 300,
    cityId: "new-york",
    tribeId: "tribe-nyc-food",
  },
];

export const casts: Cast[] = [
  ...bangaloreCasts,
  ...mumbaiCasts,
  ...delhiCasts,
  ...sanFranciscoCasts,
  ...londonCasts,
  ...newYorkCasts,
];
