import type { ChatMessage } from "@/types";
import {
  currentUser,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user8,
  user9,
  user10,
  user11,
  user12,
  user13,
  user15,
} from "./users";

// Bangalore Cycling Club chat
const cyclingClubMessages: ChatMessage[] = [
  {
    id: "msg-1",
    senderId: user1.id,
    senderName: user1.displayName,
    senderAvatar: user1.avatarUrl,
    content: "Good morning everyone! Who's up for the Saturday ride?",
    timestamp: "8:00 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user1.karma,
  },
  {
    id: "msg-2",
    senderId: currentUser.id,
    senderName: currentUser.displayName,
    senderAvatar: currentUser.avatarUrl,
    content: "Count me in! What route are we taking?",
    timestamp: "8:05 AM",
    isFromCurrentUser: true,
    type: "text",
    senderKarma: currentUser.karma,
  },
  {
    id: "msg-3",
    senderId: user3.id,
    senderName: user3.displayName,
    senderAvatar: user3.avatarUrl,
    content: "I'd suggest the Cubbon Park to Lalbagh route. It's about 12km and mostly flat.",
    timestamp: "8:10 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user3.karma,
  },
  {
    id: "msg-4",
    senderId: user15.id,
    senderName: user15.displayName,
    senderAvatar: user15.avatarUrl,
    content: "Perfect! I'll bring water bottles for everyone.",
    timestamp: "8:15 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user15.karma,
  },
  {
    id: "msg-5",
    senderId: user1.id,
    senderName: user1.displayName,
    senderAvatar: user1.avatarUrl,
    content: "Let's meet at the Cubbon Park entrance at 6:30 AM sharp!",
    timestamp: "8:20 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user1.karma,
  },
  {
    id: "msg-6",
    senderId: user2.id,
    senderName: user2.displayName,
    senderAvatar: user2.avatarUrl,
    content: "I'll be there! Also, has everyone checked their tire pressure?",
    timestamp: "8:25 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user2.karma,
  },
  {
    id: "msg-7",
    senderId: currentUser.id,
    senderName: currentUser.displayName,
    senderAvatar: currentUser.avatarUrl,
    content: "Good reminder! See everyone Saturday morning.",
    timestamp: "8:30 AM",
    isFromCurrentUser: true,
    type: "text",
    senderKarma: currentUser.karma,
  },
];

// Bangalore Foodies chat
const foodiesMessages: ChatMessage[] = [
  {
    id: "msg-8",
    senderId: user2.id,
    senderName: user2.displayName,
    senderAvatar: user2.avatarUrl,
    content: "Has anyone tried the new South Indian place on 80 Feet Road?",
    timestamp: "12:30 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user2.karma,
  },
  {
    id: "msg-9",
    senderId: user1.id,
    senderName: user1.displayName,
    senderAvatar: user1.avatarUrl,
    content: "Yes! The dosa there is incredible. Crispy and the chutney is homemade.",
    timestamp: "12:35 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user1.karma,
  },
  {
    id: "msg-10",
    senderId: currentUser.id,
    senderName: currentUser.displayName,
    senderAvatar: currentUser.avatarUrl,
    content: "Adding it to my list! What's the price range?",
    timestamp: "12:40 PM",
    isFromCurrentUser: true,
    type: "text",
    senderKarma: currentUser.karma,
  },
  {
    id: "msg-11",
    senderId: user2.id,
    senderName: user2.displayName,
    senderAvatar: user2.avatarUrl,
    content: "Very affordable, around ₹150-200 per person. They also have a great filter coffee.",
    timestamp: "12:45 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user2.karma,
  },
  {
    id: "msg-12",
    senderId: user15.id,
    senderName: user15.displayName,
    senderAvatar: user15.avatarUrl,
    content: "Do they have vegan options? I've been looking for good vegan South Indian food.",
    timestamp: "12:50 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user15.karma,
  },
  {
    id: "msg-13",
    senderId: user1.id,
    senderName: user1.displayName,
    senderAvatar: user1.avatarUrl,
    content: "Most of the menu is naturally vegan! The sambar is made without ghee too.",
    timestamp: "12:55 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user1.karma,
  },
];

// Mumbai Music Scene chat
const musicSceneMessages: ChatMessage[] = [
  {
    id: "msg-14",
    senderId: user4.id,
    senderName: user4.displayName,
    senderAvatar: user4.avatarUrl,
    content: "Big news! Prateek Kuhad is doing a secret gig in Bandra this Friday!",
    timestamp: "3:00 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user4.karma,
  },
  {
    id: "msg-15",
    senderId: user5.id,
    senderName: user5.displayName,
    senderAvatar: user5.avatarUrl,
    content: "NO WAY! Where exactly? How do we get tickets?",
    timestamp: "3:02 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user5.karma,
  },
  {
    id: "msg-16",
    senderId: user4.id,
    senderName: user4.displayName,
    senderAvatar: user4.avatarUrl,
    content: "It's at The Little Door. Only 100 tickets, first come first served. Doors open at 8 PM.",
    timestamp: "3:05 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user4.karma,
  },
  {
    id: "msg-17",
    senderId: user5.id,
    senderName: user5.displayName,
    senderAvatar: user5.avatarUrl,
    content: "I'm going early to queue up. Anyone want to come together?",
    timestamp: "3:08 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user5.karma,
  },
  {
    id: "msg-18",
    senderId: user4.id,
    senderName: user4.displayName,
    senderAvatar: user4.avatarUrl,
    content: "Let's meet at Bandra station at 6 PM and walk over together!",
    timestamp: "3:10 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user4.karma,
  },
];

// SF Tech chat
const sfTechMessages: ChatMessage[] = [
  {
    id: "msg-19",
    senderId: user8.id,
    senderName: user8.displayName,
    senderAvatar: user8.avatarUrl,
    content: "Just published our open-source community toolkit. Would love feedback from the group!",
    timestamp: "10:00 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user8.karma,
  },
  {
    id: "msg-20",
    senderId: user9.id,
    senderName: user9.displayName,
    senderAvatar: user9.avatarUrl,
    content: "This is amazing Emily! The UI components are really well designed.",
    timestamp: "10:15 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user9.karma,
  },
  {
    id: "msg-21",
    senderId: user8.id,
    senderName: user8.displayName,
    senderAvatar: user8.avatarUrl,
    content: "Thanks Alex! We're hosting a contribution workshop next week at our office. Interested?",
    timestamp: "10:20 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user8.karma,
  },
  {
    id: "msg-22",
    senderId: user9.id,
    senderName: user9.displayName,
    senderAvatar: user9.avatarUrl,
    content: "Absolutely! Can I bring a couple of designer friends? They'd love to contribute.",
    timestamp: "10:25 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user9.karma,
  },
  {
    id: "msg-23",
    senderId: user8.id,
    senderName: user8.displayName,
    senderAvatar: user8.avatarUrl,
    content: "The more the merrier! Wednesday 6 PM at our Mission District office.",
    timestamp: "10:30 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user8.karma,
  },
];

// Delhi Heritage Walks chat
const delhiHeritageMessages: ChatMessage[] = [
  {
    id: "msg-24",
    senderId: user6.id,
    senderName: user6.displayName,
    senderAvatar: user6.avatarUrl,
    content: "This Saturday's heritage walk will cover the Mughal-era stepwells of Delhi. Exciting!",
    timestamp: "9:00 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user6.karma,
  },
  {
    id: "msg-25",
    senderId: user6.id,
    senderName: user6.displayName,
    senderAvatar: user6.avatarUrl,
    content: "We'll start at Agrasen ki Baoli and end at Rajon ki Baoli in Mehrauli.",
    timestamp: "9:05 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user6.karma,
  },
  {
    id: "msg-26",
    senderId: user6.id,
    senderName: user6.displayName,
    senderAvatar: user6.avatarUrl,
    content: "Wear comfortable shoes and carry water. It's going to be a 3-hour walk.",
    timestamp: "9:10 AM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user6.karma,
  },
];

// London Community Hub chat
const londonCommunityMessages: ChatMessage[] = [
  {
    id: "msg-27",
    senderId: user10.id,
    senderName: user10.displayName,
    senderAvatar: user10.avatarUrl,
    content: "Pub quiz results are in! Team 'The Quizzard of Oz' wins again! Third week running!",
    timestamp: "10:30 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user10.karma,
  },
  {
    id: "msg-28",
    senderId: user11.id,
    senderName: user11.displayName,
    senderAvatar: user11.avatarUrl,
    content: "Unbeatable! What was the final score?",
    timestamp: "10:32 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user11.karma,
  },
  {
    id: "msg-29",
    senderId: user10.id,
    senderName: user10.displayName,
    senderAvatar: user10.avatarUrl,
    content: "42 out of 50! The music round was our secret weapon. Next week we're doing a themed quiz on London history.",
    timestamp: "10:35 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user10.karma,
  },
  {
    id: "msg-30",
    senderId: user11.id,
    senderName: user11.displayName,
    senderAvatar: user11.avatarUrl,
    content: "I need to study up! Where can I find good London history resources?",
    timestamp: "10:38 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user11.karma,
  },
  {
    id: "msg-31",
    senderId: user10.id,
    senderName: user10.displayName,
    senderAvatar: user10.avatarUrl,
    content: "The Museum of London has a brilliant online archive. Also, the Londonist YouTube channel is great!",
    timestamp: "10:40 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user10.karma,
  },
];

// NYC Eats chat
const nycEatsMessages: ChatMessage[] = [
  {
    id: "msg-32",
    senderId: user12.id,
    senderName: user12.displayName,
    senderAvatar: user12.avatarUrl,
    content: "Just tried the new ramen spot in Williamsburg. Game changer!",
    timestamp: "7:00 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user12.karma,
  },
  {
    id: "msg-33",
    senderId: user13.id,
    senderName: user13.displayName,
    senderAvatar: user13.avatarUrl,
    content: "Better than Ichiran? That's a bold claim, David!",
    timestamp: "7:05 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user13.karma,
  },
  {
    id: "msg-34",
    senderId: user12.id,
    senderName: user12.displayName,
    senderAvatar: user12.avatarUrl,
    content: "I said what I said! The tonkotsu broth is unreal. And they make their noodles in-house.",
    timestamp: "7:08 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user12.karma,
  },
  {
    id: "msg-35",
    senderId: user13.id,
    senderName: user13.displayName,
    senderAvatar: user13.avatarUrl,
    content: "OK, you've convinced me. Group dinner there this weekend? I'll make a reservation.",
    timestamp: "7:12 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user13.karma,
  },
  {
    id: "msg-36",
    senderId: user12.id,
    senderName: user12.displayName,
    senderAvatar: user12.avatarUrl,
    content: "Yes! Saturday 7 PM. I'll invite some folks from the tribe.",
    timestamp: "7:15 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user12.karma,
  },
];

// Additional general messages
const generalMessages: ChatMessage[] = [
  {
    id: "msg-37",
    senderId: user3.id,
    senderName: user3.displayName,
    senderAvatar: user3.avatarUrl,
    content: "Anyone interested in a board game night this Friday at my place in Whitefield?",
    timestamp: "6:00 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user3.karma,
  },
  {
    id: "msg-38",
    senderId: currentUser.id,
    senderName: currentUser.displayName,
    senderAvatar: currentUser.avatarUrl,
    content: "I'm in! What games are you thinking?",
    timestamp: "6:10 PM",
    isFromCurrentUser: true,
    type: "text",
    senderKarma: currentUser.karma,
  },
  {
    id: "msg-39",
    senderId: user3.id,
    senderName: user3.displayName,
    senderAvatar: user3.avatarUrl,
    content: "Settlers of Catan, Ticket to Ride, and maybe some Codenames. BYOB!",
    timestamp: "6:15 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user3.karma,
  },
  {
    id: "msg-40",
    senderId: user15.id,
    senderName: user15.displayName,
    senderAvatar: user15.avatarUrl,
    content: "I'll bring snacks! Can't wait.",
    timestamp: "6:20 PM",
    isFromCurrentUser: false,
    type: "text",
    senderKarma: user15.karma,
  },
  {
    id: "msg-41",
    senderId: currentUser.id,
    senderName: currentUser.displayName,
    senderAvatar: currentUser.avatarUrl,
    content: "This community is the best. See everyone Friday!",
    timestamp: "6:25 PM",
    isFromCurrentUser: true,
    type: "text",
    senderKarma: currentUser.karma,
  },
];

export const chatMessages: ChatMessage[] = [
  ...cyclingClubMessages,
  ...foodiesMessages,
  ...musicSceneMessages,
  ...sfTechMessages,
  ...delhiHeritageMessages,
  ...londonCommunityMessages,
  ...nycEatsMessages,
  ...generalMessages,
];
