import type {
  Conference,
  ConferenceEvent,
  ConferenceSpeaker,
  ConferenceVenue,
  ConferenceTrack,
} from "@/types";

// Shared tracks
const devConnectTracks: ConferenceTrack[] = [
  {
    id: "track-1",
    name: "DeFi & Protocols",
    description: "Decentralized finance protocols, yield strategies, and financial infrastructure",
    color: "#6366F1",
    icon: "coins",
    eventCount: 8,
  },
  {
    id: "track-2",
    name: "Infrastructure & Scaling",
    description: "Layer 2 solutions, rollups, and blockchain scaling technologies",
    color: "#14B8A6",
    icon: "server",
    eventCount: 6,
  },
  {
    id: "track-3",
    name: "Social & Identity",
    description: "Decentralized social, identity solutions, and community tooling",
    color: "#FB7185",
    icon: "users",
    eventCount: 5,
  },
  {
    id: "track-4",
    name: "Developer Tooling",
    description: "SDKs, APIs, and tools for Web3 developers",
    color: "#FB923C",
    icon: "wrench",
    eventCount: 7,
  },
];

const ethIndiaTracks: ConferenceTrack[] = [
  {
    id: "track-5",
    name: "Solidity & Smart Contracts",
    description: "Smart contract development, auditing, and best practices",
    color: "#A78BFA",
    icon: "code",
    eventCount: 10,
  },
  {
    id: "track-6",
    name: "DApp Development",
    description: "Building decentralized applications from idea to deployment",
    color: "#38BDF8",
    icon: "layout",
    eventCount: 8,
  },
];

// Venues
export const conferenceVenues: ConferenceVenue[] = [
  {
    id: "venue-1",
    name: "Bangalore International Exhibition Centre",
    address: "10th Mile, Tumkur Road, Madavara Post, Bangalore 562123",
    description: "One of India's largest exhibition venues with state-of-the-art facilities.",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=400&fit=crop",
    capacity: 5000,
    amenities: ["Wi-Fi", "Parking", "Food Court", "AV Equipment", "AC", "Wheelchair Accessible"],
    coordinates: { latitude: 13.0827, longitude: 77.4877 },
  },
  {
    id: "venue-2",
    name: "ITC Gardenia",
    address: "1, Residency Rd, Shanthala Nagar, Ashok Nagar, Bangalore 560025",
    description: "Luxury hotel and conference center in the heart of Bangalore.",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=400&fit=crop",
    capacity: 800,
    amenities: ["Wi-Fi", "Valet Parking", "Fine Dining", "AV Equipment", "AC"],
    coordinates: { latitude: 12.9716, longitude: 77.5993 },
  },
  {
    id: "venue-3",
    name: "Moscone Center",
    address: "747 Howard St, San Francisco, CA 94103",
    description: "San Francisco's premier convention and exhibition complex.",
    imageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf18c4cded?w=800&h=400&fit=crop",
    capacity: 10000,
    amenities: ["Wi-Fi", "Parking", "Food Court", "AV Equipment", "AC", "Wheelchair Accessible"],
    coordinates: { latitude: 37.7842, longitude: -122.4016 },
  },
  {
    id: "venue-4",
    name: "ExCeL London",
    address: "Royal Victoria Dock, 1 Western Gateway, London E16 1XL",
    description: "International convention and exhibition centre in east London.",
    imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=400&fit=crop",
    capacity: 8000,
    amenities: ["Wi-Fi", "Parking", "Restaurants", "AV Equipment", "AC", "DLR Access"],
    coordinates: { latitude: 51.5087, longitude: 0.0302 },
  },
  {
    id: "venue-5",
    name: "Javits Center",
    address: "429 11th Ave, New York, NY 10001",
    description: "New York City's primary convention center on the west side of Manhattan.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
    capacity: 12000,
    amenities: ["Wi-Fi", "Parking", "Food Court", "AV Equipment", "AC", "Subway Access"],
    coordinates: { latitude: 40.7579, longitude: -74.0023 },
  },
  {
    id: "venue-6",
    name: "Jio World Convention Centre",
    address: "Jio World Centre, Bandra Kurla Complex, Mumbai 400051",
    description: "India's largest and most advanced convention centre.",
    imageUrl: "https://images.unsplash.com/photo-1431540015159-0a5a14e36502?w=800&h=400&fit=crop",
    capacity: 6000,
    amenities: ["Wi-Fi", "Parking", "Dining", "AV Equipment", "AC", "Metro Access"],
    coordinates: { latitude: 19.0636, longitude: 72.8679 },
  },
];

// Speakers
export const conferenceSpeakers: ConferenceSpeaker[] = [
  {
    id: "speaker-1",
    name: "Vitalik Buterin",
    title: "Co-Founder",
    company: "Ethereum",
    bio: "Vitalik Buterin is the co-founder of Ethereum, the world's leading smart contract platform.",
    avatarUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&h=150&fit=crop",
    twitterHandle: "@VitalikButerin",
    farcasterHandle: "vitalik.eth",
    talks: ["The Future of Ethereum", "Scaling Decentralized Systems"],
    isFollowing: true,
  },
  {
    id: "speaker-2",
    name: "Balaji Srinivasan",
    title: "Angel Investor & Author",
    company: "The Network State",
    bio: "Former CTO of Coinbase and GP at a16z. Author of 'The Network State'.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    twitterHandle: "@balaborhaa",
    talks: ["Network States and Community Governance"],
    isFollowing: true,
  },
  {
    id: "speaker-3",
    name: "Stani Kulechov",
    title: "Founder & CEO",
    company: "Aave",
    bio: "Founder of Aave, one of the leading DeFi lending protocols.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
    twitterHandle: "@StaniKulechov",
    talks: ["DeFi Lending: Past, Present, and Future"],
    isFollowing: false,
  },
  {
    id: "speaker-4",
    name: "Sandeep Nailwal",
    title: "Co-Founder",
    company: "Polygon",
    bio: "Co-founder of Polygon, the leading Ethereum scaling solution.",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop",
    twitterHandle: "@sanaborhaalwal",
    talks: ["Layer 2 Scaling Solutions", "Building for a Billion Users"],
    isFollowing: true,
  },
  {
    id: "speaker-5",
    name: "Lily Liu",
    title: "President",
    company: "Web3 Foundation",
    bio: "Leading initiatives to decentralize the web.",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop",
    twitterHandle: "@LilyLiu_",
    talks: ["The Vision for Mass Adoption"],
    isFollowing: false,
  },
  {
    id: "speaker-6",
    name: "Dan Finlay",
    title: "Co-Founder",
    company: "MetaMask",
    bio: "Co-creator of MetaMask, the leading Web3 wallet with over 30 million users.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
    twitterHandle: "@danfinlay",
    talks: ["The Evolution of Web3 Wallets"],
    isFollowing: false,
  },
  {
    id: "speaker-7",
    name: "Preethi Kasireddy",
    title: "Founder & CEO",
    company: "DappCamp",
    bio: "Founder of DappCamp, a Web3 developer bootcamp. Former partner at a16z.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    twitterHandle: "@iam_preethi",
    linkedInUrl: "https://linkedin.com/in/preethikasireddy",
    talks: ["Onboarding the Next Million Web3 Developers"],
    isFollowing: true,
  },
  {
    id: "speaker-8",
    name: "Anatoly Yakovenko",
    title: "Co-Founder & CEO",
    company: "Blockchain Labs",
    bio: "Building high performance blockchain infrastructure.",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop",
    twitterHandle: "@aaborhaakovenko",
    talks: ["High Performance Blockchains", "State Compression"],
    isFollowing: true,
  },
];

// Conferences
export const conferences: Conference[] = [
  {
    id: "conf-1",
    name: "DevConnect Bangalore",
    tagline: "Building the Future of Decentralized Communities",
    description: "A week-long gathering of Ethereum builders, researchers, and community leaders in Bangalore. Featuring workshops, talks, and hackathons focused on decentralized social, DeFi, and infrastructure.",
    city: "Bangalore",
    country: "India",
    countryCode: "IN",
    startDate: "2024-08-15",
    endDate: "2024-08-22",
    venue: "Bangalore International Exhibition Centre",
    venueAddress: "10th Mile, Tumkur Road, Bangalore",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=600&fit=crop",
    logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    websiteUrl: "https://devconnect.org",
    color: "#6366F1",
    attendeeCount: 3500,
    speakerCount: 120,
    eventCount: 45,
    tracks: devConnectTracks,
    coHosts: [
      { id: "host-1", name: "Ethereum Foundation", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://ethereum.org" },
      { id: "host-2", name: "Polygon", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://polygon.technology" },
    ],
    sponsors: [
      { id: "sponsor-1", name: "Coinbase", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://coinbase.com" },
      { id: "sponsor-2", name: "Aave", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://aave.com" },
      { id: "sponsor-3", name: "MetaMask", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://metamask.io" },
      { id: "sponsor-4", name: "Uniswap", tier: "silver", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://uniswap.org" },
    ],
    isActive: true,
  },
  {
    id: "conf-2",
    name: "ETHIndia",
    tagline: "India's Largest Ethereum Hackathon",
    description: "The flagship Ethereum hackathon in India. 36 hours of building, mentoring, and prizes. Open to all skill levels.",
    city: "Bangalore",
    country: "India",
    countryCode: "IN",
    startDate: "2024-12-06",
    endDate: "2024-12-08",
    venue: "ITC Gardenia",
    venueAddress: "1, Residency Rd, Bangalore",
    imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=600&fit=crop",
    logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    websiteUrl: "https://ethindia.co",
    color: "#14B8A6",
    attendeeCount: 2000,
    speakerCount: 60,
    eventCount: 25,
    tracks: ethIndiaTracks,
    coHosts: [
      { id: "host-3", name: "Devfolio", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://devfolio.co" },
    ],
    sponsors: [
      { id: "sponsor-5", name: "Polygon", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://polygon.technology" },
      { id: "sponsor-6", name: "Filecoin", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://filecoin.io" },
    ],
    isActive: false,
  },
  {
    id: "conf-3",
    name: "Web3 SF Summit",
    tagline: "The Annual Web3 Conference",
    description: "The biggest event in the Web3 ecosystem. Keynotes, workshops, and announcements from top builders and teams.",
    city: "San Francisco",
    country: "United States",
    countryCode: "US",
    startDate: "2024-09-20",
    endDate: "2024-09-22",
    venue: "Moscone Center",
    venueAddress: "747 Howard St, San Francisco",
    imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&h=600&fit=crop",
    logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    websiteUrl: "https://web3summit.com",
    color: "#9945FF",
    attendeeCount: 5000,
    speakerCount: 150,
    eventCount: 60,
    tracks: [
      { id: "track-7", name: "DePIN", description: "Decentralized physical infrastructure networks", color: "#9945FF", icon: "globe", eventCount: 8 },
      { id: "track-8", name: "Payments", description: "Web3 payments and commerce solutions", color: "#14F195", icon: "credit-card", eventCount: 6 },
      { id: "track-9", name: "NFTs & Gaming", description: "Digital collectibles and on-chain gaming", color: "#FB7185", icon: "gamepad", eventCount: 10 },
    ],
    coHosts: [
      { id: "host-4", name: "Web3 Foundation", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://web3.foundation" },
    ],
    sponsors: [
      { id: "sponsor-7", name: "Jump Crypto", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://jumpcrypto.com" },
      { id: "sponsor-8", name: "Circle", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://circle.com" },
    ],
    isActive: true,
  },
  {
    id: "conf-4",
    name: "ETHLondon",
    tagline: "Ethereum Comes to London",
    description: "A three-day Ethereum conference and hackathon in the heart of London. Connecting the European Web3 community.",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    startDate: "2024-10-25",
    endDate: "2024-10-27",
    venue: "ExCeL London",
    venueAddress: "Royal Victoria Dock, London",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop",
    logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    websiteUrl: "https://ethlondon.com",
    color: "#38BDF8",
    attendeeCount: 3000,
    speakerCount: 90,
    eventCount: 35,
    tracks: [
      { id: "track-10", name: "ZK Proofs", description: "Zero knowledge proof systems and applications", color: "#38BDF8", icon: "shield", eventCount: 7 },
      { id: "track-11", name: "DAOs & Governance", description: "Decentralized governance and organizational design", color: "#A78BFA", icon: "vote", eventCount: 5 },
      { id: "track-12", name: "Public Goods", description: "Funding and building public goods", color: "#14B8A6", icon: "heart", eventCount: 6 },
    ],
    coHosts: [
      { id: "host-5", name: "ETHGlobal", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://ethglobal.com" },
    ],
    sponsors: [
      { id: "sponsor-9", name: "Chainlink", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://chain.link" },
      { id: "sponsor-10", name: "Optimism", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://optimism.io" },
    ],
    isActive: false,
  },
  {
    id: "conf-5",
    name: "Consensus NYC",
    tagline: "The World's Largest Crypto Event",
    description: "CoinDesk's annual flagship event bringing together the global crypto and Web3 community in New York City.",
    city: "New York",
    country: "United States",
    countryCode: "US",
    startDate: "2024-11-11",
    endDate: "2024-11-13",
    venue: "Javits Center",
    venueAddress: "429 11th Ave, New York",
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=600&fit=crop",
    logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    websiteUrl: "https://consensus.coindesk.com",
    color: "#A78BFA",
    attendeeCount: 15000,
    speakerCount: 300,
    eventCount: 100,
    tracks: [
      { id: "track-13", name: "Institutional Crypto", description: "Enterprise adoption and institutional-grade solutions", color: "#A78BFA", icon: "building", eventCount: 12 },
      { id: "track-14", name: "Regulation & Policy", description: "Crypto regulation and policy discussions", color: "#FB923C", icon: "scale", eventCount: 8 },
      { id: "track-15", name: "AI x Crypto", description: "Intersection of AI and blockchain technology", color: "#6366F1", icon: "brain", eventCount: 10 },
    ],
    coHosts: [
      { id: "host-6", name: "CoinDesk", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://coindesk.com" },
    ],
    sponsors: [
      { id: "sponsor-11", name: "BlackRock", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://blackrock.com" },
      { id: "sponsor-12", name: "Fidelity", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://fidelity.com" },
      { id: "sponsor-13", name: "Ripple", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://ripple.com" },
    ],
    isActive: false,
  },
  {
    id: "conf-6",
    name: "Web3 Mumbai",
    tagline: "India's Premier Web3 Conference",
    description: "Bringing together Web3 builders, investors, and community leaders to explore the future of decentralized technology in India's financial capital.",
    city: "Mumbai",
    country: "India",
    countryCode: "IN",
    startDate: "2024-09-05",
    endDate: "2024-09-07",
    venue: "Jio World Convention Centre",
    venueAddress: "Bandra Kurla Complex, Mumbai",
    imageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&h=600&fit=crop",
    logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    websiteUrl: "https://web3mumbai.com",
    color: "#FB7185",
    attendeeCount: 4000,
    speakerCount: 100,
    eventCount: 40,
    tracks: [
      { id: "track-16", name: "DeFi India", description: "DeFi adoption and innovation in the Indian market", color: "#FB7185", icon: "trending-up", eventCount: 8 },
      { id: "track-17", name: "Creator Economy", description: "NFTs, social tokens, and the creator economy", color: "#A78BFA", icon: "palette", eventCount: 6 },
      { id: "track-18", name: "Web3 Social", description: "Decentralized social protocols and community platforms", color: "#14B8A6", icon: "share", eventCount: 7 },
    ],
    coHosts: [
      { id: "host-7", name: "CoinDCX", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://coindcx.com" },
    ],
    sponsors: [
      { id: "sponsor-14", name: "WazirX", tier: "platinum", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://wazirx.com" },
      { id: "sponsor-15", name: "Alchemy", tier: "gold", logoUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&h=100&fit=crop", websiteUrl: "https://alchemy.com" },
    ],
    isActive: true,
  },
];

// Conference Events
export const conferenceEvents: ConferenceEvent[] = [
  // DevConnect Bangalore Events
  {
    id: "cevt-1",
    conferenceId: "conf-1",
    title: "The Future of Ethereum",
    description: "Keynote on Ethereum's roadmap, upcoming upgrades, and the path to a scalable, decentralized future.",
    track: devConnectTracks[0],
    venue: conferenceVenues[0],
    startTime: "2024-08-15T09:00:00Z",
    endTime: "2024-08-15T10:30:00Z",
    speakers: [conferenceSpeakers[0]],
    capacity: 2000,
    registeredCount: 1850,
    requiresRegistration: true,
    isKeynote: true,
    tags: ["ethereum", "roadmap", "keynote"],
    isBookmarked: true,
    isRegistered: true,
  },
  {
    id: "cevt-2",
    conferenceId: "conf-1",
    title: "Network States and Community Governance",
    description: "How digital communities are forming new governance models and what it means for the future of coordination.",
    track: devConnectTracks[2],
    venue: conferenceVenues[0],
    startTime: "2024-08-15T11:00:00Z",
    endTime: "2024-08-15T12:00:00Z",
    speakers: [conferenceSpeakers[1]],
    capacity: 500,
    registeredCount: 489,
    requiresRegistration: true,
    isKeynote: false,
    tags: ["governance", "network-state", "community"],
    isBookmarked: true,
    isRegistered: false,
  },
  {
    id: "cevt-3",
    conferenceId: "conf-1",
    title: "DeFi Lending: Past, Present, and Future",
    description: "A deep dive into the evolution of DeFi lending protocols and what comes next.",
    track: devConnectTracks[0],
    venue: conferenceVenues[0],
    startTime: "2024-08-16T14:00:00Z",
    endTime: "2024-08-16T15:00:00Z",
    speakers: [conferenceSpeakers[2]],
    capacity: 400,
    registeredCount: 356,
    requiresRegistration: false,
    isKeynote: false,
    tags: ["defi", "lending", "aave"],
    isBookmarked: false,
    isRegistered: false,
  },
  {
    id: "cevt-4",
    conferenceId: "conf-1",
    title: "Layer 2 Scaling Solutions",
    description: "Comparing approaches to scaling Ethereum: rollups, sidechains, and emerging solutions.",
    track: devConnectTracks[1],
    venue: conferenceVenues[0],
    startTime: "2024-08-17T10:00:00Z",
    endTime: "2024-08-17T11:30:00Z",
    speakers: [conferenceSpeakers[3]],
    capacity: 600,
    registeredCount: 534,
    requiresRegistration: true,
    isKeynote: false,
    tags: ["layer2", "scaling", "polygon"],
    isBookmarked: false,
    isRegistered: true,
  },
  // Web3 SF Summit Events
  {
    id: "cevt-5",
    conferenceId: "conf-3",
    title: "The Vision for Mass Adoption",
    description: "Building for a billion users with fast, cheap, and reliable infrastructure.",
    venue: conferenceVenues[2],
    startTime: "2024-09-20T09:00:00Z",
    endTime: "2024-09-20T10:00:00Z",
    speakers: [conferenceSpeakers[4]],
    capacity: 3000,
    registeredCount: 2800,
    requiresRegistration: true,
    isKeynote: true,
    tags: ["web3", "adoption", "keynote"],
    isBookmarked: true,
    isRegistered: true,
  },
  {
    id: "cevt-6",
    conferenceId: "conf-3",
    title: "High Performance Blockchains",
    description: "Technical deep dive into blockchain architecture and upcoming improvements.",
    venue: conferenceVenues[2],
    startTime: "2024-09-20T14:00:00Z",
    endTime: "2024-09-20T15:30:00Z",
    speakers: [conferenceSpeakers[7]],
    capacity: 1500,
    registeredCount: 1200,
    requiresRegistration: false,
    isKeynote: false,
    tags: ["web3", "performance", "architecture"],
    isBookmarked: false,
    isRegistered: false,
  },
  // ETHLondon Events
  {
    id: "cevt-7",
    conferenceId: "conf-4",
    title: "The Evolution of Web3 Wallets",
    description: "From seed phrases to smart accounts: the journey toward user-friendly Web3 access.",
    venue: conferenceVenues[3],
    startTime: "2024-10-25T11:00:00Z",
    endTime: "2024-10-25T12:00:00Z",
    speakers: [conferenceSpeakers[5]],
    capacity: 800,
    registeredCount: 650,
    requiresRegistration: true,
    isKeynote: false,
    tags: ["wallets", "UX", "metamask"],
    isBookmarked: true,
    isRegistered: false,
  },
  // Consensus NYC Events
  {
    id: "cevt-8",
    conferenceId: "conf-5",
    title: "Onboarding the Next Million Web3 Developers",
    description: "Strategies and tools for bringing traditional developers into the Web3 ecosystem.",
    venue: conferenceVenues[4],
    startTime: "2024-11-11T10:00:00Z",
    endTime: "2024-11-11T11:00:00Z",
    speakers: [conferenceSpeakers[6]],
    capacity: 1000,
    registeredCount: 890,
    requiresRegistration: true,
    isKeynote: false,
    tags: ["developers", "education", "onboarding"],
    isBookmarked: false,
    isRegistered: false,
  },
  // ETHIndia Events
  {
    id: "cevt-9",
    conferenceId: "conf-2",
    title: "Building for a Billion Users",
    description: "How to design and build dApps that can scale to serve India's massive population.",
    track: ethIndiaTracks[1],
    venue: conferenceVenues[1],
    startTime: "2024-12-06T10:00:00Z",
    endTime: "2024-12-06T11:30:00Z",
    speakers: [conferenceSpeakers[3], conferenceSpeakers[6]],
    capacity: 500,
    registeredCount: 478,
    requiresRegistration: true,
    isKeynote: true,
    tags: ["india", "scaling", "dapps"],
    isBookmarked: true,
    isRegistered: true,
  },
  // Web3 Mumbai Events
  {
    id: "cevt-10",
    conferenceId: "conf-6",
    title: "DeFi Adoption in India",
    description: "Exploring the opportunities and challenges of DeFi adoption in the Indian market.",
    venue: conferenceVenues[5],
    startTime: "2024-09-05T09:00:00Z",
    endTime: "2024-09-05T10:30:00Z",
    speakers: [conferenceSpeakers[2], conferenceSpeakers[3]],
    capacity: 1200,
    registeredCount: 980,
    requiresRegistration: true,
    isKeynote: true,
    tags: ["defi", "india", "adoption"],
    isBookmarked: false,
    isRegistered: false,
  },
];
