import type { Crowdfund } from "@/types";
import {
  currentUser,
  user2,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
  user10,
  user11,
  user12,
  user13,
} from "./users";

const bangaloreCrowdfunds: Crowdfund[] = [
  {
    id: "cf-blr-1",
    user: currentUser,
    title: "Koramangala Community Library",
    description: "Building a free community library with reading room, Wi-Fi, and after-school study space for kids in the neighborhood.",
    icon: "book",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=400&fit=crop",
    location: "Koramangala 5th Block",
    goal: 500000,
    raised: 342000,
    contributors: 156,
    timeAgo: "3 days ago",
  },
  {
    id: "cf-blr-2",
    user: user2,
    title: "HSR Layout Dog Park",
    description: "Creating a dedicated off-leash dog park with agility equipment, water stations, and shaded seating areas.",
    icon: "paw",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=400&fit=crop",
    location: "HSR Layout Sector 2",
    goal: 300000,
    raised: 178000,
    contributors: 89,
    timeAgo: "1 week ago",
  },
];

const mumbaiCrowdfunds: Crowdfund[] = [
  {
    id: "cf-mum-1",
    user: user4,
    title: "Bandra Skatepark Project",
    description: "Building Mumbai's first community skatepark with ramps, rails, and a beginner's section. Open to all ages.",
    icon: "zap",
    imageUrl: "https://images.unsplash.com/photo-1564429238961-bf8f8be8c8cd?w=800&h=400&fit=crop",
    location: "Bandra Reclamation",
    goal: 800000,
    raised: 534000,
    contributors: 234,
    timeAgo: "5 days ago",
  },
  {
    id: "cf-mum-2",
    user: user5,
    title: "Andheri Street Art Festival",
    description: "Funding a week-long street art festival transforming bare walls into vibrant murals across Andheri.",
    icon: "palette",
    imageUrl: "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&h=400&fit=crop",
    location: "Andheri West",
    goal: 200000,
    raised: 156000,
    contributors: 123,
    timeAgo: "2 days ago",
  },
];

const delhiCrowdfunds: Crowdfund[] = [
  {
    id: "cf-del-1",
    user: user6,
    title: "Delhi Heritage Audio Guide",
    description: "Creating a free multilingual audio guide app for Old Delhi heritage sites. Supporting 8 languages.",
    icon: "headphones",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=400&fit=crop",
    location: "Old Delhi",
    goal: 400000,
    raised: 289000,
    contributors: 178,
    timeAgo: "1 week ago",
  },
  {
    id: "cf-del-2",
    user: user7,
    title: "Saket Urban Forest",
    description: "Transforming an empty lot into a mini urban forest using the Miyawaki method. Planting 500 native trees.",
    icon: "tree",
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=400&fit=crop",
    location: "Saket, South Delhi",
    goal: 350000,
    raised: 98000,
    contributors: 67,
    timeAgo: "4 days ago",
  },
];

const sanFranciscoCrowdfunds: Crowdfund[] = [
  {
    id: "cf-sf-1",
    user: user8,
    title: "Mission District Solar Panels",
    description: "Installing solar panels on the community center roof to power free Wi-Fi and charging stations for the neighborhood.",
    icon: "sun",
    imageUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=400&fit=crop",
    location: "Mission District Community Center",
    goal: 25000,
    raised: 18900,
    contributors: 145,
    timeAgo: "6 days ago",
  },
  {
    id: "cf-sf-2",
    user: user9,
    title: "Free Coding Bootcamp Fund",
    description: "Sponsoring 20 underrepresented students for a 12-week intensive coding bootcamp in SoMa.",
    icon: "code",
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=400&fit=crop",
    location: "SoMa, San Francisco",
    goal: 50000,
    raised: 37800,
    contributors: 198,
    timeAgo: "3 days ago",
  },
];

const londonCrowdfunds: Crowdfund[] = [
  {
    id: "cf-ldn-1",
    user: user10,
    title: "Shoreditch Community Kitchen",
    description: "Opening a pay-what-you-can community kitchen serving fresh, locally sourced meals to anyone in need.",
    icon: "utensils",
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=400&fit=crop",
    location: "Shoreditch, East London",
    goal: 15000,
    raised: 12400,
    contributors: 267,
    timeAgo: "1 week ago",
  },
  {
    id: "cf-ldn-2",
    user: user11,
    title: "Camden Music Studio for Youth",
    description: "Building a free recording studio and rehearsal space for young musicians in Camden. Professional equipment included.",
    icon: "music",
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=400&fit=crop",
    location: "Camden Town, London",
    goal: 20000,
    raised: 14500,
    contributors: 189,
    timeAgo: "5 days ago",
  },
];

const newYorkCrowdfunds: Crowdfund[] = [
  {
    id: "cf-nyc-1",
    user: user12,
    title: "Williamsburg Rooftop Farm",
    description: "Converting a warehouse rooftop into a community farm producing fresh vegetables for local food banks.",
    icon: "sprout",
    imageUrl: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&h=400&fit=crop",
    location: "Williamsburg, Brooklyn",
    goal: 35000,
    raised: 28900,
    contributors: 312,
    timeAgo: "4 days ago",
  },
  {
    id: "cf-nyc-2",
    user: user13,
    title: "East Village Dance Studio",
    description: "Opening a community dance studio offering free classes in salsa, hip-hop, and contemporary dance.",
    icon: "heart",
    imageUrl: "https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=800&h=400&fit=crop",
    location: "East Village, Manhattan",
    goal: 45000,
    raised: 31200,
    contributors: 234,
    timeAgo: "1 week ago",
  },
];

export const crowdfunds: Record<string, Crowdfund[]> = {
  bangalore: bangaloreCrowdfunds,
  mumbai: mumbaiCrowdfunds,
  delhi: delhiCrowdfunds,
  "san-francisco": sanFranciscoCrowdfunds,
  london: londonCrowdfunds,
  "new-york": newYorkCrowdfunds,
};
