import type { ExploreItem } from "@/types";

const bangaloreExplore: ExploreItem[] = [
  {
    id: "exp-blr-1",
    type: "event",
    title: "Koramangala Street Food Festival",
    description: "A weekend celebration of Bangalore's diverse street food culture. 30+ vendors, live music, and cooking demos.",
    icon: "utensils",
    color: "#FB7185",
    participants: 450,
    location: "Koramangala 4th Block",
    timeAgo: "Starting in 2 days",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=400&fit=crop",
    isTrending: true,
    cityId: "bangalore",
    coordinates: { latitude: 12.9352, longitude: 77.6245 },
  },
  {
    id: "exp-blr-2",
    type: "event",
    title: "Cubbon Park Sunrise Yoga",
    description: "Free community yoga session in Cubbon Park every Saturday. All levels welcome. Bring your own mat.",
    icon: "heart",
    color: "#14B8A6",
    participants: 120,
    location: "Cubbon Park, Bangalore",
    timeAgo: "Every Saturday 6am",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=400&fit=crop",
    isTrending: false,
    cityId: "bangalore",
    coordinates: { latitude: 12.9763, longitude: 77.5929 },
  },
];

const mumbaiExplore: ExploreItem[] = [
  {
    id: "exp-mum-1",
    type: "event",
    title: "Marine Drive Music Festival",
    description: "Live performances by indie artists along Marine Drive. Food stalls, art installations, and sunset views.",
    icon: "music",
    color: "#A78BFA",
    participants: 800,
    location: "Marine Drive, Mumbai",
    timeAgo: "This weekend",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=400&fit=crop",
    isTrending: true,
    cityId: "mumbai",
    coordinates: { latitude: 18.9432, longitude: 72.8235 },
  },
  {
    id: "exp-mum-2",
    type: "event",
    title: "Bandra Photography Walk",
    description: "Guided photography walk through Bandra's iconic lanes, street art, and heritage bungalows.",
    icon: "camera",
    color: "#38BDF8",
    participants: 45,
    location: "Bandra West, Mumbai",
    timeAgo: "Tomorrow 7am",
    imageUrl: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&h=400&fit=crop",
    isTrending: false,
    cityId: "mumbai",
    coordinates: { latitude: 19.0544, longitude: 72.8202 },
  },
];

const delhiExplore: ExploreItem[] = [
  {
    id: "exp-del-1",
    type: "event",
    title: "Old Delhi Heritage Walk & Food Tour",
    description: "Walk through Mughal-era monuments, hidden temples, and end with a legendary Chandni Chowk food crawl.",
    icon: "landmark",
    color: "#6366F1",
    participants: 60,
    location: "Jama Masjid, Old Delhi",
    timeAgo: "This Saturday 8am",
    imageUrl: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=400&fit=crop",
    isTrending: true,
    cityId: "delhi",
    coordinates: { latitude: 28.6507, longitude: 77.2334 },
  },
  {
    id: "exp-del-2",
    type: "event",
    title: "Lodhi Garden Art & Picnic",
    description: "Community picnic at Lodhi Gardens with plein air painting, book exchange, and acoustic music.",
    icon: "palette",
    color: "#FB923C",
    participants: 90,
    location: "Lodhi Gardens, New Delhi",
    timeAgo: "Sunday 10am",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=400&fit=crop",
    isTrending: false,
    cityId: "delhi",
    coordinates: { latitude: 28.5931, longitude: 77.2197 },
  },
];

const sanFranciscoExplore: ExploreItem[] = [
  {
    id: "exp-sf-1",
    type: "event",
    title: "Mission District Block Party",
    description: "Annual block party with live DJs, taco trucks, craft beer, and community art projects.",
    icon: "party-popper",
    color: "#FB7185",
    participants: 350,
    location: "Valencia Street, SF",
    timeAgo: "Next Saturday",
    imageUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=400&fit=crop",
    isTrending: true,
    cityId: "san-francisco",
    coordinates: { latitude: 37.7599, longitude: -122.4214 },
  },
  {
    id: "exp-sf-2",
    type: "event",
    title: "Golden Gate Park Tech Meetup",
    description: "Outdoor networking event for tech professionals. Lightning talks, demos, and picnic lunch provided.",
    icon: "rocket",
    color: "#14B8A6",
    participants: 180,
    location: "Golden Gate Park, SF",
    timeAgo: "This Friday 5pm",
    imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=400&fit=crop",
    isTrending: false,
    cityId: "san-francisco",
    coordinates: { latitude: 37.7694, longitude: -122.4862 },
  },
];

const londonExplore: ExploreItem[] = [
  {
    id: "exp-ldn-1",
    type: "event",
    title: "Shoreditch Street Food Festival",
    description: "International street food, craft cocktails, and live bands in Shoreditch's best venues.",
    icon: "utensils",
    color: "#FB923C",
    participants: 600,
    location: "Shoreditch, London",
    timeAgo: "This weekend",
    imageUrl: "https://images.unsplash.com/photo-1574180045827-681f8a1a9622?w=800&h=400&fit=crop",
    isTrending: true,
    cityId: "london",
    coordinates: { latitude: 51.5235, longitude: -0.0773 },
  },
  {
    id: "exp-ldn-2",
    type: "event",
    title: "Thames Path Community Run",
    description: "5K charity run along the Thames Path from Tower Bridge to Greenwich. All abilities welcome.",
    icon: "footprints",
    color: "#38BDF8",
    participants: 200,
    location: "Tower Bridge, London",
    timeAgo: "Next Sunday 9am",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=400&fit=crop",
    isTrending: false,
    cityId: "london",
    coordinates: { latitude: 51.5055, longitude: -0.0754 },
  },
];

const newYorkExplore: ExploreItem[] = [
  {
    id: "exp-nyc-1",
    type: "event",
    title: "Brooklyn Bridge Sunset Walk",
    description: "Guided walking tour across Brooklyn Bridge at sunset. Photography tips, history, and post-walk dinner in DUMBO.",
    icon: "camera",
    color: "#A78BFA",
    participants: 75,
    location: "Brooklyn Bridge, NYC",
    timeAgo: "Friday 6pm",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&h=400&fit=crop",
    isTrending: true,
    cityId: "new-york",
    coordinates: { latitude: 40.7061, longitude: -73.9969 },
  },
  {
    id: "exp-nyc-2",
    type: "event",
    title: "Central Park Community Potluck",
    description: "Monthly potluck in Central Park. Bring a dish, meet your neighbors, play lawn games.",
    icon: "utensils",
    color: "#FB7185",
    participants: 150,
    location: "Sheep Meadow, Central Park",
    timeAgo: "This Saturday 12pm",
    imageUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&h=400&fit=crop",
    isTrending: false,
    cityId: "new-york",
    coordinates: { latitude: 40.7722, longitude: -73.9755 },
  },
];

export const exploreItems: ExploreItem[] = [
  ...bangaloreExplore,
  ...mumbaiExplore,
  ...delhiExplore,
  ...sanFranciscoExplore,
  ...londonExplore,
  ...newYorkExplore,
];
