import type { UserProfile, ActivityItem, NotificationItem } from "@/types";
import { cities } from "./cities";
import { currentUser, achievements } from "./users";

const bangaloreCity = cities.find((c) => c.id === "bangalore")!;

export const userProfile: UserProfile = {
  name: currentUser.displayName,
  username: currentUser.username,
  bio: currentUser.bio ?? "",
  avatar: currentUser.avatarUrl,
  coverImage: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200&h=400&fit=crop",
  location: currentUser.location ?? "Bangalore",
  city: bangaloreCity,
  joinedDate: currentUser.joinedDate ?? "2024-01-01",
  stats: {
    tweets: 47,
    events: 12,
    tasks: 8,
    polls: 15,
    tipsReceived: 89,
    tipsGiven: 34,
  },
  badges: [
    "Early Adopter",
    "Community Builder",
    "Event Organizer",
    "Helpful Neighbor",
  ],
  karma: currentUser.karma!,
  isVerified: currentUser.isVerified,
};

export const activityItems: ActivityItem[] = [
  {
    id: "act-1",
    type: "tweet",
    title: "Shared a photo of the rooftop cafe in Koramangala",
    time: "2 hours ago",
    likes: 42,
    comments: 8,
    tips: 3,
  },
  {
    id: "act-2",
    type: "event",
    title: "Organized Koramangala Street Food Festival",
    time: "1 day ago",
    attendees: 450,
  },
  {
    id: "act-3",
    type: "task",
    title: "Helped with park cleanup in Koramangala",
    time: "2 days ago",
    status: "completed",
  },
  {
    id: "act-4",
    type: "tweet",
    title: "Posted about the new cycling route through Cubbon Park",
    time: "3 days ago",
    likes: 89,
    comments: 12,
    tips: 7,
  },
  {
    id: "act-5",
    type: "event",
    title: "Attended Bangalore Tech Meetup",
    time: "4 days ago",
    attendees: 120,
  },
  {
    id: "act-6",
    type: "tweet",
    title: "Shared terrace garden progress photos",
    time: "5 days ago",
    likes: 156,
    comments: 23,
    tips: 12,
  },
  {
    id: "act-7",
    type: "task",
    title: "Volunteered for dog walking in Indiranagar",
    time: "1 week ago",
    status: "completed",
  },
  {
    id: "act-8",
    type: "event",
    title: "Co-hosted community yoga session at Lalbagh",
    time: "1 week ago",
    attendees: 60,
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "notif-1",
    type: "like",
    user: { id: "u2", displayName: "John Doe", avatarUrl: "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=150&h=150&fit=crop" },
    message: "liked your tweet about the rooftop cafe",
    time: "5 minutes ago",
    isRead: false,
  },
  {
    id: "notif-2",
    type: "comment",
    user: { id: "u3", displayName: "Sarah Kumar", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop" },
    message: "commented: \"Love the vibes! Was there last weekend.\"",
    time: "10 minutes ago",
    isRead: false,
  },
  {
    id: "notif-3",
    type: "follow",
    user: { id: "u5", displayName: "Priya Mehta", avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop" },
    message: "started following you",
    time: "30 minutes ago",
    isRead: false,
  },
  {
    id: "notif-4",
    type: "event",
    user: { id: "u2", displayName: "John Doe", avatarUrl: "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=150&h=150&fit=crop" },
    message: "invited you to Saturday Morning Ride",
    time: "1 hour ago",
    isRead: false,
  },
  {
    id: "notif-5",
    type: "like",
    user: { id: "u4", displayName: "Mike Johnson", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop" },
    message: "liked your tweet about cycling in Cubbon Park",
    time: "1 hour ago",
    isRead: true,
  },
  {
    id: "notif-6",
    type: "channel",
    user: { id: "u16", displayName: "Lisa Brown", avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop" },
    message: "posted in Bangalore Fitness Tribe",
    time: "2 hours ago",
    isRead: true,
  },
  {
    id: "notif-7",
    type: "comment",
    user: { id: "u2", displayName: "John Doe", avatarUrl: "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=150&h=150&fit=crop" },
    message: "replied to your comment in Cycling Club",
    time: "2 hours ago",
    isRead: true,
  },
  {
    id: "notif-8",
    type: "like",
    user: { id: "u3", displayName: "Sarah Kumar", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop" },
    message: "tipped you ₹50 for your food review",
    time: "3 hours ago",
    isRead: true,
  },
  {
    id: "notif-9",
    type: "follow",
    user: { id: "u9", displayName: "Emily Chen", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop" },
    message: "started following you",
    time: "4 hours ago",
    isRead: true,
  },
  {
    id: "notif-10",
    type: "event",
    user: { id: "u16", displayName: "Lisa Brown", avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop" },
    message: "is hosting Sunrise Yoga at Lalbagh tomorrow",
    time: "5 hours ago",
    isRead: true,
  },
  {
    id: "notif-11",
    type: "like",
    user: { id: "u6", displayName: "Arjun Patel", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop" },
    message: "liked your tweet about street food",
    time: "6 hours ago",
    isRead: true,
  },
  {
    id: "notif-12",
    type: "comment",
    user: { id: "u4", displayName: "Mike Johnson", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop" },
    message: "commented on your hackathon post",
    time: "7 hours ago",
    isRead: true,
  },
  {
    id: "notif-13",
    type: "channel",
    user: { id: "u3", displayName: "Sarah Kumar", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop" },
    message: "shared a photo in Bangalore Foodies",
    time: "8 hours ago",
    isRead: true,
  },
  {
    id: "notif-14",
    type: "follow",
    user: { id: "u11", displayName: "James Wilson", avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop" },
    message: "started following you",
    time: "10 hours ago",
    isRead: true,
  },
  {
    id: "notif-15",
    type: "like",
    user: { id: "u7", displayName: "Neha Sharma", avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop" },
    message: "liked your post about community building",
    time: "12 hours ago",
    isRead: true,
  },
  {
    id: "notif-16",
    type: "event",
    user: { id: "u2", displayName: "John Doe", avatarUrl: "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=150&h=150&fit=crop" },
    message: "RSVP'd to your Street Food Festival event",
    time: "14 hours ago",
    isRead: true,
  },
  {
    id: "notif-17",
    type: "comment",
    user: { id: "u16", displayName: "Lisa Brown", avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop" },
    message: "commented: \"Can I bring my friend who's visiting?\"",
    time: "1 day ago",
    isRead: true,
  },
  {
    id: "notif-18",
    type: "like",
    user: { id: "u13", displayName: "David Kim", avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop" },
    message: "liked your garden photo",
    time: "1 day ago",
    isRead: true,
  },
  {
    id: "notif-19",
    type: "follow",
    user: { id: "u14", displayName: "Maria Garcia", avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop" },
    message: "started following you",
    time: "1 day ago",
    isRead: true,
  },
  {
    id: "notif-20",
    type: "channel",
    user: { id: "u2", displayName: "John Doe", avatarUrl: "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=150&h=150&fit=crop" },
    message: "started a new discussion in Cycling Club",
    time: "1 day ago",
    isRead: true,
  },
  {
    id: "notif-21",
    type: "like",
    user: { id: "u10", displayName: "Alex Rodriguez", avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop" },
    message: "tipped you ₹100 for your community event",
    time: "2 days ago",
    isRead: true,
  },
  {
    id: "notif-22",
    type: "comment",
    user: { id: "u7", displayName: "Neha Sharma", avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop" },
    message: "mentioned you in a heritage walk post",
    time: "2 days ago",
    isRead: true,
  },
  {
    id: "notif-23",
    type: "event",
    user: { id: "u3", displayName: "Sarah Kumar", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop" },
    message: "created a new event: Terrace Gardening Workshop",
    time: "2 days ago",
    isRead: true,
  },
  {
    id: "notif-24",
    type: "follow",
    user: { id: "u15", displayName: "Ryan O'Connor", avatarUrl: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop" },
    message: "started following you",
    time: "3 days ago",
    isRead: true,
  },
  {
    id: "notif-25",
    type: "like",
    user: { id: "u12", displayName: "Sophie Taylor", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop" },
    message: "liked your yoga session tweet",
    time: "3 days ago",
    isRead: true,
  },
  {
    id: "notif-26",
    type: "channel",
    user: { id: "u4", displayName: "Mike Johnson", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop" },
    message: "posted a poll in Bangalore Tech Community",
    time: "4 days ago",
    isRead: true,
  },
  {
    id: "notif-27",
    type: "comment",
    user: { id: "u6", displayName: "Arjun Patel", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop" },
    message: "replied to your comment about Mumbai food",
    time: "4 days ago",
    isRead: true,
  },
  {
    id: "notif-28",
    type: "event",
    user: { id: "u4", displayName: "Mike Johnson", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop" },
    message: "is organizing a hackathon this weekend",
    time: "5 days ago",
    isRead: true,
  },
  {
    id: "notif-29",
    type: "like",
    user: { id: "u8", displayName: "Rahul Verma", avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop" },
    message: "liked your community library crowdfund",
    time: "5 days ago",
    isRead: true,
  },
  {
    id: "notif-30",
    type: "follow",
    user: { id: "u5", displayName: "Priya Mehta", avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop" },
    message: "recommended you to their followers",
    time: "1 week ago",
    isRead: true,
  },
];
