import type { Tribe } from "@/types";

// Bangalore Tribes
const bangaloreTribes: Tribe[] = [
  {
    id: "tribe-blr-cycling",
    cityId: "bangalore",
    name: "Bangalore Cycling Club",
    description: "Weekend rides, route sharing, and cycling advocacy for a more bike-friendly Bangalore.",
    category: "cycling",
    icon: "bike",
    color: "#6366F1",
    imageUrl: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=400&fit=crop",
    members: 1245,
    isPrivate: false,
    moderators: ["u2", "u1"],
    rules: [
      "Always wear a helmet on group rides",
      "Share route maps before rides",
      "Be respectful and encouraging to all skill levels",
      "No motorized vehicles in cycling events",
    ],
    subchannels: [
      { id: "sc-blr-c1", name: "General", description: "General cycling chat", icon: "message-circle", color: "#6366F1", members: 1245 },
      { id: "sc-blr-c2", name: "Routes", description: "Share and discover routes", icon: "map", color: "#14B8A6", members: 890 },
      { id: "sc-blr-c3", name: "Gear Talk", description: "Discuss bikes and equipment", icon: "wrench", color: "#FB923C", members: 654 },
      { id: "sc-blr-c4", name: "Events", description: "Upcoming rides and meetups", icon: "calendar", color: "#FB7185", members: 1100 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-blr-food",
    cityId: "bangalore",
    name: "Bangalore Foodies",
    description: "Discovering hidden gems, street food, and the best restaurants across Bangalore.",
    category: "food",
    icon: "utensils",
    color: "#FB7185",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=400&fit=crop",
    members: 2340,
    isPrivate: false,
    moderators: ["u1", "u3"],
    rules: [
      "Share honest reviews",
      "Include location and price range",
      "No promotional posts without mod approval",
      "Be respectful of all dietary preferences",
    ],
    subchannels: [
      { id: "sc-blr-f1", name: "General", description: "Food discussions", icon: "message-circle", color: "#FB7185", members: 2340 },
      { id: "sc-blr-f2", name: "Reviews", description: "Restaurant reviews", icon: "star", color: "#FB923C", members: 1567 },
      { id: "sc-blr-f3", name: "Recipes", description: "Share your recipes", icon: "book-open", color: "#14B8A6", members: 890 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-blr-tech",
    cityId: "bangalore",
    name: "Bangalore Tech Community",
    description: "Developers, designers, and tech enthusiasts building the future in India's Silicon Valley.",
    category: "tech",
    icon: "code",
    color: "#14B8A6",
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=400&fit=crop",
    members: 3456,
    isPrivate: false,
    moderators: ["u4", "u1"],
    rules: [
      "Share knowledge freely",
      "No recruiting without mod approval",
      "Keep discussions constructive",
      "Credit original authors when sharing",
    ],
    subchannels: [
      { id: "sc-blr-t1", name: "General", description: "Tech discussions", icon: "message-circle", color: "#14B8A6", members: 3456 },
      { id: "sc-blr-t2", name: "Web3", description: "Blockchain & crypto", icon: "link", color: "#A78BFA", members: 1234 },
      { id: "sc-blr-t3", name: "Hackathons", description: "Hackathon coordination", icon: "trophy", color: "#FB923C", members: 2100 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-blr-fitness",
    cityId: "bangalore",
    name: "Bangalore Fitness Tribe",
    description: "Yoga, running, gym workouts, and outdoor fitness activities across the Garden City.",
    category: "fitness",
    icon: "dumbbell",
    color: "#FB923C",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=400&fit=crop",
    members: 1890,
    isPrivate: false,
    moderators: ["u16", "u3"],
    rules: [
      "Encourage, don't judge fitness levels",
      "Share workout tips and routines",
      "Safety first in all activities",
      "Certified trainers only for paid sessions",
    ],
    subchannels: [
      { id: "sc-blr-fi1", name: "General", description: "Fitness chat", icon: "message-circle", color: "#FB923C", members: 1890 },
      { id: "sc-blr-fi2", name: "Yoga", description: "Yoga sessions & tips", icon: "heart", color: "#FB7185", members: 890 },
      { id: "sc-blr-fi3", name: "Running", description: "Running groups & routes", icon: "footprints", color: "#14B8A6", members: 1200 },
    ],
    isJoined: true,
  },
];

// Mumbai Tribes
const mumbaiTribes: Tribe[] = [
  {
    id: "tribe-mum-food",
    cityId: "mumbai",
    name: "Mumbai Street Food Lovers",
    description: "From vada pav to pani puri, exploring the best street food Mumbai has to offer.",
    category: "food",
    icon: "utensils",
    color: "#FB7185",
    imageUrl: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=800&h=400&fit=crop",
    members: 4567,
    isPrivate: false,
    moderators: ["u5", "u6"],
    rules: [
      "Include hygiene ratings in reviews",
      "Share locations with landmarks",
      "No food shaming",
      "Support local vendors",
    ],
    subchannels: [
      { id: "sc-mum-f1", name: "General", description: "Food chat", icon: "message-circle", color: "#FB7185", members: 4567 },
      { id: "sc-mum-f2", name: "Street Food", description: "Street food finds", icon: "map-pin", color: "#FB923C", members: 3200 },
      { id: "sc-mum-f3", name: "Reviews", description: "Restaurant reviews", icon: "star", color: "#14B8A6", members: 2100 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-mum-fitness",
    cityId: "mumbai",
    name: "Mumbai Trekkers & Runners",
    description: "Weekend treks, marathon training, and outdoor fitness across Mumbai and the Western Ghats.",
    category: "fitness",
    icon: "mountain",
    color: "#14B8A6",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=400&fit=crop",
    members: 2890,
    isPrivate: false,
    moderators: ["u5", "u6"],
    rules: [
      "Safety briefing before every trek",
      "Carry enough water and snacks",
      "Leave no trace policy",
      "First-aid kit mandatory for organizers",
    ],
    subchannels: [
      { id: "sc-mum-fi1", name: "General", description: "Fitness discussions", icon: "message-circle", color: "#14B8A6", members: 2890 },
      { id: "sc-mum-fi2", name: "Treks", description: "Trek planning", icon: "mountain", color: "#6366F1", members: 2100 },
      { id: "sc-mum-fi3", name: "Running", description: "Marathon & run groups", icon: "footprints", color: "#FB923C", members: 1500 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-mum-music",
    cityId: "mumbai",
    name: "Mumbai Music Scene",
    description: "Live gigs, jam sessions, Bollywood nights, and indie music in the city of dreams.",
    category: "music",
    icon: "music",
    color: "#A78BFA",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=400&fit=crop",
    members: 3456,
    isPrivate: false,
    moderators: ["u5"],
    rules: [
      "Share gig details with venue info",
      "Support local artists",
      "No pirated music sharing",
      "Constructive feedback only",
    ],
    subchannels: [
      { id: "sc-mum-m1", name: "General", description: "Music chat", icon: "message-circle", color: "#A78BFA", members: 3456 },
      { id: "sc-mum-m2", name: "Gigs", description: "Upcoming live events", icon: "calendar", color: "#FB7185", members: 2800 },
      { id: "sc-mum-m3", name: "Jam Sessions", description: "Find musicians to jam", icon: "guitar", color: "#14B8A6", members: 1200 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-mum-photography",
    cityId: "mumbai",
    name: "Mumbai Shutterbugs",
    description: "Street photography, landscape shots, and photo walks exploring every corner of Mumbai.",
    category: "photography",
    icon: "camera",
    color: "#38BDF8",
    imageUrl: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&h=400&fit=crop",
    members: 1678,
    isPrivate: false,
    moderators: ["u6"],
    rules: [
      "Credit photographers when sharing",
      "Constructive critiques welcome",
      "Get consent for portraits",
      "Share camera settings for educational posts",
    ],
    subchannels: [
      { id: "sc-mum-p1", name: "General", description: "Photography chat", icon: "message-circle", color: "#38BDF8", members: 1678 },
      { id: "sc-mum-p2", name: "Photo Walks", description: "Organized walks", icon: "map", color: "#FB923C", members: 1100 },
      { id: "sc-mum-p3", name: "Critique", description: "Get feedback on photos", icon: "eye", color: "#A78BFA", members: 890 },
    ],
    isJoined: false,
  },
];

// Delhi Tribes
const delhiTribes: Tribe[] = [
  {
    id: "tribe-del-food",
    cityId: "delhi",
    name: "Delhi Food Trail",
    description: "Chandni Chowk paranthas to Khan Market bistros, covering all of Delhi's legendary food scene.",
    category: "food",
    icon: "utensils",
    color: "#FB923C",
    imageUrl: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=800&h=400&fit=crop",
    members: 5678,
    isPrivate: false,
    moderators: ["u7", "u8"],
    rules: [
      "Include area and nearest metro station",
      "Share prices for budget planning",
      "Vegetarian/non-veg tags required",
      "Be supportive of all culinary traditions",
    ],
    subchannels: [
      { id: "sc-del-f1", name: "General", description: "Food discussions", icon: "message-circle", color: "#FB923C", members: 5678 },
      { id: "sc-del-f2", name: "Old Delhi", description: "Old Delhi food spots", icon: "map-pin", color: "#FB7185", members: 3400 },
      { id: "sc-del-f3", name: "Cafes", description: "Cafe recommendations", icon: "coffee", color: "#14B8A6", members: 2100 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-del-heritage",
    cityId: "delhi",
    name: "Delhi Heritage Walks",
    description: "Exploring Delhi's 1000+ years of history through guided walks, talks, and cultural events.",
    category: "travel",
    icon: "landmark",
    color: "#6366F1",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=400&fit=crop",
    members: 2345,
    isPrivate: false,
    moderators: ["u7"],
    rules: [
      "Respect all historical sites",
      "Share historically accurate information",
      "Photography allowed unless restricted",
      "Wear comfortable walking shoes",
    ],
    subchannels: [
      { id: "sc-del-h1", name: "General", description: "Heritage discussions", icon: "message-circle", color: "#6366F1", members: 2345 },
      { id: "sc-del-h2", name: "Walks", description: "Upcoming heritage walks", icon: "footprints", color: "#FB923C", members: 1800 },
      { id: "sc-del-h3", name: "History", description: "Historical discussions", icon: "book", color: "#14B8A6", members: 1200 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-del-arts",
    cityId: "delhi",
    name: "Delhi Arts & Culture",
    description: "Sufi nights, art exhibitions, theatre, and all things creative in the capital.",
    category: "arts",
    icon: "palette",
    color: "#FB7185",
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=400&fit=crop",
    members: 1890,
    isPrivate: false,
    moderators: ["u7", "u8"],
    rules: [
      "Support local artists",
      "Share event details with ticket info",
      "Constructive feedback only",
      "Credit artists when sharing work",
    ],
    subchannels: [
      { id: "sc-del-a1", name: "General", description: "Arts & culture chat", icon: "message-circle", color: "#FB7185", members: 1890 },
      { id: "sc-del-a2", name: "Events", description: "Cultural events", icon: "calendar", color: "#A78BFA", members: 1400 },
      { id: "sc-del-a3", name: "Gallery", description: "Share artwork", icon: "image", color: "#14B8A6", members: 900 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-del-green",
    cityId: "delhi",
    name: "Green Delhi Initiative",
    description: "Tree plantation drives, urban gardening, and environmental action to make Delhi greener.",
    category: "general",
    icon: "leaf",
    color: "#14B8A6",
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=400&fit=crop",
    members: 1456,
    isPrivate: false,
    moderators: ["u8"],
    rules: [
      "Evidence-based environmental discussions",
      "No political debates",
      "Share practical sustainability tips",
      "Volunteer-friendly environment",
    ],
    subchannels: [
      { id: "sc-del-g1", name: "General", description: "Green discussions", icon: "message-circle", color: "#14B8A6", members: 1456 },
      { id: "sc-del-g2", name: "Plantation", description: "Tree planting drives", icon: "tree", color: "#6366F1", members: 980 },
      { id: "sc-del-g3", name: "Gardening", description: "Urban gardening tips", icon: "sprout", color: "#FB923C", members: 750 },
    ],
    isJoined: false,
  },
];

// San Francisco Tribes
const sanFranciscoTribes: Tribe[] = [
  {
    id: "tribe-sf-tech",
    cityId: "san-francisco",
    name: "SF Tech & Startups",
    description: "Founders, developers, and innovators shaping the future from the Bay Area.",
    category: "tech",
    icon: "rocket",
    color: "#14B8A6",
    imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=400&fit=crop",
    members: 4567,
    isPrivate: false,
    moderators: ["u9", "u10"],
    rules: [
      "No spam or self-promotion without value",
      "Share knowledge generously",
      "Respect NDA and confidential information",
      "Constructive feedback culture",
    ],
    subchannels: [
      { id: "sc-sf-t1", name: "General", description: "Tech discussions", icon: "message-circle", color: "#14B8A6", members: 4567 },
      { id: "sc-sf-t2", name: "Startups", description: "Startup talk", icon: "rocket", color: "#6366F1", members: 3200 },
      { id: "sc-sf-t3", name: "Web3", description: "Crypto & blockchain", icon: "link", color: "#A78BFA", members: 1800 },
      { id: "sc-sf-t4", name: "Jobs", description: "Job board", icon: "briefcase", color: "#FB923C", members: 2900 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-sf-fitness",
    cityId: "san-francisco",
    name: "SF Outdoor Fitness",
    description: "Trail runs, beach workouts, and outdoor fitness in the most beautiful city by the bay.",
    category: "fitness",
    icon: "dumbbell",
    color: "#FB923C",
    imageUrl: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=800&h=400&fit=crop",
    members: 2345,
    isPrivate: false,
    moderators: ["u9"],
    rules: [
      "All fitness levels welcome",
      "Safety first on trails",
      "Share routes and difficulty levels",
      "Be encouraging and supportive",
    ],
    subchannels: [
      { id: "sc-sf-fi1", name: "General", description: "Fitness chat", icon: "message-circle", color: "#FB923C", members: 2345 },
      { id: "sc-sf-fi2", name: "Trail Running", description: "Trail run coordination", icon: "mountain", color: "#14B8A6", members: 1500 },
      { id: "sc-sf-fi3", name: "Beach Workouts", description: "Beach fitness sessions", icon: "sun", color: "#38BDF8", members: 890 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-sf-food",
    cityId: "san-francisco",
    name: "SF Food & Wine",
    description: "Farm-to-table, food trucks, Michelin stars, and everything in between in the SF food scene.",
    category: "food",
    icon: "wine",
    color: "#FB7185",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=400&fit=crop",
    members: 3456,
    isPrivate: false,
    moderators: ["u10"],
    rules: [
      "Include dietary info in recommendations",
      "Support local restaurants",
      "Share honest reviews",
      "Include price ranges",
    ],
    subchannels: [
      { id: "sc-sf-fo1", name: "General", description: "Food chat", icon: "message-circle", color: "#FB7185", members: 3456 },
      { id: "sc-sf-fo2", name: "Restaurants", description: "Restaurant finds", icon: "utensils", color: "#FB923C", members: 2800 },
      { id: "sc-sf-fo3", name: "Wine", description: "Wine recommendations", icon: "wine", color: "#A78BFA", members: 1200 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-sf-arts",
    cityId: "san-francisco",
    name: "SF Street Art & Murals",
    description: "Celebrating and preserving SF's vibrant street art culture from the Mission to the Tenderloin.",
    category: "arts",
    icon: "palette",
    color: "#A78BFA",
    imageUrl: "https://images.unsplash.com/photo-1510137600163-2729bc6959e4?w=800&h=400&fit=crop",
    members: 1234,
    isPrivate: false,
    moderators: ["u10"],
    rules: [
      "Credit artists always",
      "Share locations for art tours",
      "Report vandalism, not art",
      "Support emerging artists",
    ],
    subchannels: [
      { id: "sc-sf-a1", name: "General", description: "Art discussions", icon: "message-circle", color: "#A78BFA", members: 1234 },
      { id: "sc-sf-a2", name: "Tours", description: "Art walk routes", icon: "map", color: "#14B8A6", members: 800 },
      { id: "sc-sf-a3", name: "New Art", description: "Newly discovered art", icon: "eye", color: "#FB923C", members: 950 },
    ],
    isJoined: false,
  },
];

// London Tribes
const londonTribes: Tribe[] = [
  {
    id: "tribe-ldn-food",
    cityId: "london",
    name: "London Foodies",
    description: "Borough Market to Brick Lane, discovering the best eats across London's diverse food scene.",
    category: "food",
    icon: "utensils",
    color: "#FB7185",
    imageUrl: "https://images.unsplash.com/photo-1574180045827-681f8a1a9622?w=800&h=400&fit=crop",
    members: 5678,
    isPrivate: false,
    moderators: ["u11", "u12"],
    rules: [
      "Include nearest tube station",
      "Share price ranges",
      "Tag dietary requirements",
      "Support independent restaurants",
    ],
    subchannels: [
      { id: "sc-ldn-f1", name: "General", description: "Food chat", icon: "message-circle", color: "#FB7185", members: 5678 },
      { id: "sc-ldn-f2", name: "Markets", description: "Food market finds", icon: "shopping-bag", color: "#FB923C", members: 3400 },
      { id: "sc-ldn-f3", name: "Pubs", description: "Best pub grub", icon: "beer", color: "#14B8A6", members: 2800 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-ldn-arts",
    cityId: "london",
    name: "London Arts & Theatre",
    description: "West End shows, gallery openings, and creative workshops across the capital.",
    category: "arts",
    icon: "drama",
    color: "#A78BFA",
    imageUrl: "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&h=400&fit=crop",
    members: 3456,
    isPrivate: false,
    moderators: ["u12"],
    rules: [
      "No spoilers without warning",
      "Share booking links and discount codes",
      "Support fringe and independent theatre",
      "Constructive reviews encouraged",
    ],
    subchannels: [
      { id: "sc-ldn-a1", name: "General", description: "Arts chat", icon: "message-circle", color: "#A78BFA", members: 3456 },
      { id: "sc-ldn-a2", name: "Theatre", description: "Theatre reviews", icon: "drama", color: "#FB7185", members: 2200 },
      { id: "sc-ldn-a3", name: "Galleries", description: "Exhibition reviews", icon: "image", color: "#14B8A6", members: 1800 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-ldn-cycling",
    cityId: "london",
    name: "London Cycling Network",
    description: "Commuting tips, weekend rides, and cycling advocacy across Greater London.",
    category: "cycling",
    icon: "bike",
    color: "#38BDF8",
    imageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=800&h=400&fit=crop",
    members: 2890,
    isPrivate: false,
    moderators: ["u11"],
    rules: [
      "Always wear a helmet",
      "Follow the Highway Code",
      "Share bike maintenance tips",
      "Report dangerous road conditions",
    ],
    subchannels: [
      { id: "sc-ldn-c1", name: "General", description: "Cycling chat", icon: "message-circle", color: "#38BDF8", members: 2890 },
      { id: "sc-ldn-c2", name: "Commuting", description: "Commute routes & tips", icon: "map", color: "#6366F1", members: 2100 },
      { id: "sc-ldn-c3", name: "Weekend Rides", description: "Leisure ride planning", icon: "sun", color: "#FB923C", members: 1500 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-ldn-community",
    cityId: "london",
    name: "London Community Hub",
    description: "Pub quizzes, volunteer opportunities, and neighborhood events making London feel like home.",
    category: "general",
    icon: "users",
    color: "#6366F1",
    imageUrl: "https://images.unsplash.com/photo-1576073719676-aa95576db207?w=800&h=400&fit=crop",
    members: 4123,
    isPrivate: false,
    moderators: ["u11", "u12"],
    rules: [
      "Be kind and welcoming",
      "Share events with full details",
      "No commercial spam",
      "Help newcomers feel at home",
    ],
    subchannels: [
      { id: "sc-ldn-co1", name: "General", description: "Community chat", icon: "message-circle", color: "#6366F1", members: 4123 },
      { id: "sc-ldn-co2", name: "Events", description: "Local events", icon: "calendar", color: "#FB7185", members: 3200 },
      { id: "sc-ldn-co3", name: "Volunteering", description: "Volunteer opportunities", icon: "heart", color: "#14B8A6", members: 1800 },
    ],
    isJoined: true,
  },
];

// New York Tribes
const newYorkTribes: Tribe[] = [
  {
    id: "tribe-nyc-food",
    cityId: "new-york",
    name: "NYC Eats",
    description: "Pizza debates, dumpling discoveries, and the best bites in every borough.",
    category: "food",
    icon: "pizza",
    color: "#FB7185",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=400&fit=crop",
    members: 6789,
    isPrivate: false,
    moderators: ["u13", "u14"],
    rules: [
      "Respect all boroughs equally",
      "Include subway directions",
      "No chain restaurant posts",
      "Share the love for local spots",
    ],
    subchannels: [
      { id: "sc-nyc-f1", name: "General", description: "Food chat", icon: "message-circle", color: "#FB7185", members: 6789 },
      { id: "sc-nyc-f2", name: "Pizza Wars", description: "The great pizza debate", icon: "pizza", color: "#FB923C", members: 4500 },
      { id: "sc-nyc-f3", name: "Hidden Gems", description: "Undiscovered spots", icon: "sparkles", color: "#A78BFA", members: 3200 },
    ],
    isJoined: true,
  },
  {
    id: "tribe-nyc-fitness",
    cityId: "new-york",
    name: "NYC Runners & Fitness",
    description: "Central Park runs, Brooklyn Bridge workouts, and fitness challenges across the five boroughs.",
    category: "fitness",
    icon: "dumbbell",
    color: "#14B8A6",
    imageUrl: "https://images.unsplash.com/photo-1474224017946-8f6217e7d90a?w=800&h=400&fit=crop",
    members: 3456,
    isPrivate: false,
    moderators: ["u13"],
    rules: [
      "All fitness levels welcome",
      "Share routes with difficulty levels",
      "Safety in numbers for early/late runs",
      "Encourage and motivate each other",
    ],
    subchannels: [
      { id: "sc-nyc-fi1", name: "General", description: "Fitness chat", icon: "message-circle", color: "#14B8A6", members: 3456 },
      { id: "sc-nyc-fi2", name: "Running", description: "Running groups", icon: "footprints", color: "#FB923C", members: 2400 },
      { id: "sc-nyc-fi3", name: "Outdoor", description: "Outdoor workouts", icon: "sun", color: "#38BDF8", members: 1800 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-nyc-arts",
    cityId: "new-york",
    name: "NYC Arts & Dance",
    description: "Gallery openings, dance classes, street performers, and creative expression in the city that never sleeps.",
    category: "arts",
    icon: "palette",
    color: "#A78BFA",
    imageUrl: "https://images.unsplash.com/photo-1485182708500-e8f1f318ba72?w=800&h=400&fit=crop",
    members: 2890,
    isPrivate: false,
    moderators: ["u14"],
    rules: [
      "Support local artists",
      "Share event details and pricing",
      "Credit creators always",
      "Free events get priority posting",
    ],
    subchannels: [
      { id: "sc-nyc-a1", name: "General", description: "Arts discussions", icon: "message-circle", color: "#A78BFA", members: 2890 },
      { id: "sc-nyc-a2", name: "Dance", description: "Dance classes & events", icon: "music", color: "#FB7185", members: 1800 },
      { id: "sc-nyc-a3", name: "Galleries", description: "Gallery & museum visits", icon: "image", color: "#14B8A6", members: 1500 },
    ],
    isJoined: false,
  },
  {
    id: "tribe-nyc-music",
    cityId: "new-york",
    name: "NYC Live Music",
    description: "Jazz clubs, indie venues, and live performances across New York's legendary music scene.",
    category: "music",
    icon: "music",
    color: "#6366F1",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=400&fit=crop",
    members: 4567,
    isPrivate: false,
    moderators: ["u13", "u14"],
    rules: [
      "Share gig info with venue and time",
      "No ticket scalping",
      "Support emerging artists",
      "Record with permission only",
    ],
    subchannels: [
      { id: "sc-nyc-m1", name: "General", description: "Music chat", icon: "message-circle", color: "#6366F1", members: 4567 },
      { id: "sc-nyc-m2", name: "Jazz", description: "Jazz scene", icon: "music", color: "#A78BFA", members: 2100 },
      { id: "sc-nyc-m3", name: "Indie", description: "Indie & alternative", icon: "guitar", color: "#FB923C", members: 2800 },
    ],
    isJoined: false,
  },
];

export const tribes: Tribe[] = [
  ...bangaloreTribes,
  ...mumbaiTribes,
  ...delhiTribes,
  ...sanFranciscoTribes,
  ...londonTribes,
  ...newYorkTribes,
];
